# Generated by Django 6.0.7 on 2026-07-29 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followups', '0001_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='opportunities.opportunity'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['next_followup_date'], name='followups_next_fo_502b77_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['opportunity', '-created_at'], name='followups_opportu_49a2a2_idx'),
        ),
    ]
