# Generated by Django 6.0.7 on 2026-07-29 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sales_rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_94f025_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='leads_priorit_375942_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_rep', 'status'], name='leads_assigne_72090d_idx'),
        ),
    ]
